name: Email Step Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f2000851@ds.study.iitm.ac.in
        run: echo "Hello, world!"
